### ISSUE TITLE
INTER-chromosomal interactions are not calculated

### ISSUE THREAD

**Issue by hreypar** [Gabrielstav/HiEdge#3]
Hi! 

There's an error when the `interaction_type` parameter in the config is set to `inter` or `mixed`. 

The input files for the specified resolutions are found, they are read and converted to a dask dataframe, etc, the values for intra chromosomal interactions are calculated and the output is written, but then there's an issue with the InterPValueCalculator

```
Traceback (most recent call last):
  File "HiEdge/main.py", line 91, in <module>
    pipeline.run()
  File "HiEdge/main.py", line 49, in run
    statistical_output = self._execute_in_parallel(filtered_interactions, StatController)
  File "HiEdge/main.py", line 65, in _execute_in_parallel
    delayed_runs = [delayed(controller_class(self.config, input_obj).run()) for input_obj in inputs]
  File "HiEdge/main.py", line 65, in <listcomp>
    delayed_runs = [delayed(controller_class(self.config, input_obj).run()) for input_obj in inputs]
  File "HiEdge/src/statistics/stat_controller.py", line 31, in run
    return self._process_inter_stats()
  File "HiEdge/src/statistics/stat_controller.py", line 61, in _process_inter_stats
    pvals = self._process_inter_pvals(inter_stats)
  File "HiEdge/src/statistics/stat_controller.py", line 97, in _process_inter_pvals
    pval_calculator = InterPValueCalculator(pval_input, self.config, self.metadata, self.metadata.max_possible_interaction_count_inter)
AttributeError: 'Metadata' object has no attribute 'max_possible_interaction_count_inter'. Did you mean: 'max_possible_interacting_bins_inter'?

``` 
and honestly I have not reasoned it (i.e. which part of the model is this supposed to be?), but sure enough, the inter p value calculator is set up to use [max_possible_interaction_count_inter](https://github.com/Gabrielstav/HiEdge/blob/8a64da8584a43b32c7e00e9381b5080b7a4b79da/src/statistics/stat_controller.py#L97) so if you change that (the suggested attribute change) and rerun 

```
Traceback (most recent call last):
  File "HiEdge/main.py", line 91, in <module>
    pipeline.run()
  File "HiEdge/main.py", line 49, in run
    statistical_output = self._execute_in_parallel(filtered_interactions, StatController)
  File "HiEdge/main.py", line 65, in _execute_in_parallel
    delayed_runs = [delayed(controller_class(self.config, input_obj).run()) for input_obj in inputs]
  File "HiEdge/main.py", line 65, in <listcomp>
    delayed_runs = [delayed(controller_class(self.config, input_obj).run()) for input_obj in inputs]
  File "HiEdge/src/statistics/stat_controller.py", line 31, in run
    return self._process_inter_stats()
  File "HiEdge/src/statistics/stat_controller.py", line 61, in _process_inter_stats
    pvals = self._process_inter_pvals(inter_stats)
  File "HiEdge/src/statistics/stat_controller.py", line 97, in _process_inter_pvals
    pval_calculator = InterPValueCalculator(pval_input, self.config, self.metadata, self.metadata.max_possible_interacting_bins_inter)
  File "HiEdge/src/statistics/pvals.py", line 193, in __init__
    self.interChrProb = data.interChrProb
  File "hiedge/lib/python3.10/site-packages/pydantic/main.py", line 828, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'Config' object has no attribute 'interChrProb'
```

I don't know, is `interChrProb` even supposed to be defined through the configuration file? 
have you successfully calculated significance for inter-chromosomal interactions?

**Comment by Gabrielstav** [comment]
Hi Helena, thanks for bringing this to my attention - I didn't really test interhcromosomal data much when I worked on this tool, and had some bugs. It's fixed now - sorry for the long wait. 

LMK if there are more issues. 

Fixed by PR #4.
